# Generated by Django 5.2 on 2025-04-16 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(default='Lelystad', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('property_type', models.CharField(choices=[('huurwoning', 'Huurwoning'), ('koopwoning', 'Koopwoning'), ('kantoor', 'Kantoor'), ('koepel', 'Koepel'), ('tm-centrum', 'TM-centrum'), ('anders', 'Anders')], max_length=20)),
                ('interest_solar', models.BooleanField(default=False)),
                ('interest_battery', models.BooleanField(default=False)),
                ('interest_sharing', models.BooleanField(default=False)),
                ('interest_charger', models.BooleanField(default=False)),
                ('interest_info_only', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Aanmelding ontvangen'), ('confirmed', 'E-mail bevestigd'), ('tibber_connected', 'Tibber gekoppeld'), ('active', 'Actief'), ('inactive', 'Inactief')], default='pending', max_length=20)),
                ('tibber_token', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
